"""MCC → category: the merchant's REGISTERED line of business as a signal.

A card network Merchant Category Code is what the merchant told its
acquirer it does — a warehouse (4225) is storage whatever the descriptor
says. Plaid passes it through as `merchant_category_code` when the bank
sends it (a minority of institutions do), and it is sharper than a name
guess, so it sits between Plaid's own confident answer and the machine
rules: it fires only where Plaid was LOW/MEDIUM or generic, and a user rule
still beats it. Only codes we are confident about are mapped; anything
else is left to the layers below.

Values are (primary, detailed suffix) in Plaid's personal-finance-category
vocabulary, so `detailed = f"{primary}_{suffix}"`.
"""
from __future__ import annotations

_M: dict[str, tuple[str, str]] = {
    # food & drink
    "5411": ("FOOD_AND_DRINK", "GROCERIES"),
    "5422": ("FOOD_AND_DRINK", "GROCERIES"),
    "5441": ("FOOD_AND_DRINK", "GROCERIES"),
    "5451": ("FOOD_AND_DRINK", "GROCERIES"),
    "5462": ("FOOD_AND_DRINK", "OTHER_FOOD_AND_DRINK"),
    "5499": ("FOOD_AND_DRINK", "GROCERIES"),
    "5811": ("FOOD_AND_DRINK", "RESTAURANT"),
    "5812": ("FOOD_AND_DRINK", "RESTAURANT"),
    "5813": ("FOOD_AND_DRINK", "BEER_WINE_AND_LIQUOR"),
    "5814": ("FOOD_AND_DRINK", "FAST_FOOD"),
    "5921": ("FOOD_AND_DRINK", "BEER_WINE_AND_LIQUOR"),
    # transportation
    "4111": ("TRANSPORTATION", "PUBLIC_TRANSIT"),
    "4121": ("TRANSPORTATION", "TAXIS_AND_RIDE_SHARES"),
    "4131": ("TRANSPORTATION", "PUBLIC_TRANSIT"),
    "4784": ("TRANSPORTATION", "TOLLS"),
    "5541": ("TRANSPORTATION", "GAS"),
    "5542": ("TRANSPORTATION", "GAS"),
    "7523": ("TRANSPORTATION", "PARKING"),
    "5511": ("TRANSPORTATION", "OTHER_TRANSPORTATION"),
    "5571": ("TRANSPORTATION", "BIKES_AND_SCOOTERS"),
    "5940": ("TRANSPORTATION", "BIKES_AND_SCOOTERS"),
    # travel
    "4511": ("TRAVEL", "FLIGHTS"),
    "4722": ("TRAVEL", "OTHER_TRAVEL"),
    "7011": ("TRAVEL", "LODGING"),
    "7012": ("TRAVEL", "LODGING"),
    "7512": ("TRAVEL", "RENTAL_CARS"),
    # rent & utilities
    "4814": ("RENT_AND_UTILITIES", "TELEPHONE"),
    "4816": ("RENT_AND_UTILITIES", "INTERNET_AND_CABLE"),
    "4899": ("RENT_AND_UTILITIES", "INTERNET_AND_CABLE"),
    "4900": ("RENT_AND_UTILITIES", "GAS_AND_ELECTRICITY"),
    "6513": ("RENT_AND_UTILITIES", "RENT"),
    # medical
    "0742": ("MEDICAL", "VETERINARY_SERVICES"),
    "5912": ("MEDICAL", "PHARMACIES_AND_SUPPLEMENTS"),
    "8011": ("MEDICAL", "PRIMARY_CARE"),
    "8021": ("MEDICAL", "DENTAL_CARE"),
    "8031": ("MEDICAL", "PRIMARY_CARE"),
    "8041": ("MEDICAL", "OTHER_MEDICAL"),
    "8042": ("MEDICAL", "EYE_CARE"),
    "8043": ("MEDICAL", "EYE_CARE"),
    "8049": ("MEDICAL", "OTHER_MEDICAL"),
    "8050": ("MEDICAL", "NURSING_CARE"),
    "8062": ("MEDICAL", "OTHER_MEDICAL"),
    "8071": ("MEDICAL", "OTHER_MEDICAL"),
    "8099": ("MEDICAL", "OTHER_MEDICAL"),
    # personal care
    "7211": ("PERSONAL_CARE", "LAUNDRY_AND_DRY_CLEANING"),
    "7216": ("PERSONAL_CARE", "LAUNDRY_AND_DRY_CLEANING"),
    "7230": ("PERSONAL_CARE", "HAIR_AND_BEAUTY"),
    "7298": ("PERSONAL_CARE", "HAIR_AND_BEAUTY"),
    "7997": ("PERSONAL_CARE", "GYMS_AND_FITNESS_CENTERS"),
    "5977": ("PERSONAL_CARE", "HAIR_AND_BEAUTY"),
    # entertainment
    "5735": ("ENTERTAINMENT", "MUSIC_AND_AUDIO"),
    "5815": ("ENTERTAINMENT", "OTHER_ENTERTAINMENT"),
    "5816": ("ENTERTAINMENT", "VIDEO_GAMES"),
    "5817": ("ENTERTAINMENT", "OTHER_ENTERTAINMENT"),
    "5818": ("ENTERTAINMENT", "OTHER_ENTERTAINMENT"),
    "7832": ("ENTERTAINMENT", "TV_AND_MOVIES"),
    "7841": ("ENTERTAINMENT", "TV_AND_MOVIES"),
    "7922": ("ENTERTAINMENT", "OTHER_ENTERTAINMENT"),
    "7929": ("ENTERTAINMENT", "MUSIC_AND_AUDIO"),
    "7941": ("ENTERTAINMENT", "SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS"),
    "7991": ("ENTERTAINMENT", "SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS"),
    "7994": ("ENTERTAINMENT", "VIDEO_GAMES"),
    "7995": ("ENTERTAINMENT", "CASINOS_AND_GAMBLING"),
    "7996": ("ENTERTAINMENT", "SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS"),
    "7998": ("ENTERTAINMENT", "SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS"),
    "7999": ("ENTERTAINMENT", "OTHER_ENTERTAINMENT"),
    # general merchandise
    "5300": ("GENERAL_MERCHANDISE", "SUPERSTORES"),
    "5310": ("GENERAL_MERCHANDISE", "DISCOUNT_STORES"),
    "5311": ("GENERAL_MERCHANDISE", "DEPARTMENT_STORES"),
    "5331": ("GENERAL_MERCHANDISE", "DISCOUNT_STORES"),
    "5399": ("GENERAL_MERCHANDISE", "OTHER_GENERAL_MERCHANDISE"),
    "5611": ("GENERAL_MERCHANDISE", "CLOTHING_AND_ACCESSORIES"),
    "5621": ("GENERAL_MERCHANDISE", "CLOTHING_AND_ACCESSORIES"),
    "5631": ("GENERAL_MERCHANDISE", "CLOTHING_AND_ACCESSORIES"),
    "5641": ("GENERAL_MERCHANDISE", "CLOTHING_AND_ACCESSORIES"),
    "5651": ("GENERAL_MERCHANDISE", "CLOTHING_AND_ACCESSORIES"),
    "5661": ("GENERAL_MERCHANDISE", "CLOTHING_AND_ACCESSORIES"),
    "5691": ("GENERAL_MERCHANDISE", "CLOTHING_AND_ACCESSORIES"),
    "5699": ("GENERAL_MERCHANDISE", "CLOTHING_AND_ACCESSORIES"),
    "5732": ("GENERAL_MERCHANDISE", "ELECTRONICS"),
    "5941": ("GENERAL_MERCHANDISE", "SPORTING_GOODS"),
    "5942": ("GENERAL_MERCHANDISE", "BOOKSTORES_AND_NEWSSTANDS"),
    "5943": ("GENERAL_MERCHANDISE", "OFFICE_SUPPLIES"),
    "5945": ("GENERAL_MERCHANDISE", "OTHER_GENERAL_MERCHANDISE"),
    "5947": ("GENERAL_MERCHANDISE", "GIFTS_AND_NOVELTIES"),
    "5964": ("GENERAL_MERCHANDISE", "ONLINE_MARKETPLACES"),
    "5965": ("GENERAL_MERCHANDISE", "ONLINE_MARKETPLACES"),
    "5966": ("GENERAL_MERCHANDISE", "ONLINE_MARKETPLACES"),
    "5967": ("GENERAL_MERCHANDISE", "ONLINE_MARKETPLACES"),
    "5968": ("GENERAL_MERCHANDISE", "ONLINE_MARKETPLACES"),
    "5969": ("GENERAL_MERCHANDISE", "ONLINE_MARKETPLACES"),
    "5992": ("GENERAL_MERCHANDISE", "GIFTS_AND_NOVELTIES"),
    "5995": ("GENERAL_MERCHANDISE", "PET_SUPPLIES"),
    "5999": ("GENERAL_MERCHANDISE", "OTHER_GENERAL_MERCHANDISE"),
    # home improvement
    "1520": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "1711": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "1731": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "1740": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "1750": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "1761": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "1771": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "0780": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "7342": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "7349": ("HOME_IMPROVEMENT", "REPAIR_AND_MAINTENANCE"),
    "5200": ("HOME_IMPROVEMENT", "HARDWARE"),
    "5211": ("HOME_IMPROVEMENT", "HARDWARE"),
    "5251": ("HOME_IMPROVEMENT", "HARDWARE"),
    "5261": ("HOME_IMPROVEMENT", "OTHER_HOME_IMPROVEMENT"),
    "5712": ("HOME_IMPROVEMENT", "FURNITURE"),
    "5713": ("HOME_IMPROVEMENT", "FURNITURE"),
    "5714": ("HOME_IMPROVEMENT", "FURNITURE"),
    "5719": ("HOME_IMPROVEMENT", "FURNITURE"),
    "5722": ("HOME_IMPROVEMENT", "OTHER_HOME_IMPROVEMENT"),
    # general services
    "4215": ("GENERAL_SERVICES", "POSTAGE_AND_SHIPPING"),
    "4225": ("GENERAL_SERVICES", "STORAGE"),
    "6300": ("GENERAL_SERVICES", "INSURANCE"),
    "5960": ("GENERAL_SERVICES", "INSURANCE"),
    "7311": ("GENERAL_SERVICES", "OTHER_GENERAL_SERVICES"),
    "7372": ("GENERAL_SERVICES", "OTHER_GENERAL_SERVICES"),
    "7375": ("GENERAL_SERVICES", "OTHER_GENERAL_SERVICES"),
    "7392": ("GENERAL_SERVICES", "CONSULTING_AND_LEGAL"),
    "7399": ("GENERAL_SERVICES", "OTHER_GENERAL_SERVICES"),
    "7531": ("GENERAL_SERVICES", "AUTOMOTIVE"),
    "7534": ("GENERAL_SERVICES", "AUTOMOTIVE"),
    "7538": ("GENERAL_SERVICES", "AUTOMOTIVE"),
    "7542": ("GENERAL_SERVICES", "AUTOMOTIVE"),
    "7549": ("GENERAL_SERVICES", "AUTOMOTIVE"),
    "8111": ("GENERAL_SERVICES", "CONSULTING_AND_LEGAL"),
    "8211": ("GENERAL_SERVICES", "EDUCATION"),
    "8220": ("GENERAL_SERVICES", "EDUCATION"),
    "8241": ("GENERAL_SERVICES", "EDUCATION"),
    "8244": ("GENERAL_SERVICES", "EDUCATION"),
    "8249": ("GENERAL_SERVICES", "EDUCATION"),
    "8299": ("GENERAL_SERVICES", "EDUCATION"),
    "8351": ("GENERAL_SERVICES", "CHILDCARE"),
    "8931": ("GENERAL_SERVICES", "ACCOUNTING_AND_FINANCIAL_PLANNING"),
    "9402": ("GENERAL_SERVICES", "POSTAGE_AND_SHIPPING"),
    # government & non-profit
    "8398": ("GOVERNMENT_AND_NON_PROFIT", "DONATIONS"),
    "8661": ("GOVERNMENT_AND_NON_PROFIT", "DONATIONS"),
    "9211": ("GOVERNMENT_AND_NON_PROFIT", "GOVERNMENT_DEPARTMENTS_AND_AGENCIES"),
    "9222": ("GOVERNMENT_AND_NON_PROFIT", "GOVERNMENT_DEPARTMENTS_AND_AGENCIES"),
    "9311": ("GOVERNMENT_AND_NON_PROFIT", "TAX_PAYMENT"),
    "9399": ("GOVERNMENT_AND_NON_PROFIT", "GOVERNMENT_DEPARTMENTS_AND_AGENCIES"),
    "9405": ("GOVERNMENT_AND_NON_PROFIT", "GOVERNMENT_DEPARTMENTS_AND_AGENCIES"),
}
# airlines and car-rental brands occupy whole ranges of their own
for _c in range(3000, 3300):
    _M.setdefault(str(_c), ("TRAVEL", "FLIGHTS"))
for _c in range(3351, 3442):
    _M.setdefault(str(_c), ("TRAVEL", "RENTAL_CARS"))
for _c in range(3501, 3836):
    _M.setdefault(str(_c), ("TRAVEL", "LODGING"))


def category_for(code: str | None) -> tuple[str, str] | None:
    """(primary, detailed) for an MCC we are confident about, else None."""
    if not code:
        return None
    m = _M.get(str(code).strip().lstrip("0").rjust(4, "0"))
    return (m[0], f"{m[0]}_{m[1]}") if m else None


def label(code: str | None) -> str | None:
    """A short human label for the detail panel ("4225 · storage")."""
    m = category_for(code)
    if not m:
        return None
    return m[1].removeprefix(m[0] + "_").replace("_", " ").lower()
