"""Portable tenant-data export (CCPA/GDPR data portability).

The admin console normally shows NO tenant data (the doctrine).
Export is the deliberate, audited exception: an operator (acting on a
data-subject request, or a consented support case) produces a portable
archive of a tenant's own data. Reads run through the tenant-scoped RLS
connection, so the query set can never leak across tenants.

The archive is a ZIP of JSON — one file per domain table plus a
manifest. Receipt/statement BLOBS are exported as metadata rows only
(filename, kind, size, txn); the raw bytes are intentionally omitted to
keep the archive portable and small (an operator who needs the images
uses the tenant's own Settings export). Secrets (encrypted tokens, TOTP
seeds, password hashes) are NEVER exported.
"""

from __future__ import annotations

import datetime as dt
import io
import json
import zipfile

from . import ext
from .db import tenancy

# Tenant-scoped tables worth exporting, with the columns to keep. `None`
# means "every column except the excluded secret/blob set below". Ordered
# for a human reading the archive, not by FK.
_EXCLUDE_COLS = {
    "access_token", "public_token", "token_hash", "totp_secret",
    "password_hash", "recovery_code", "secret", "data_key", "raw_bytes",
    "image", "image_optimized", "content", "p256dh", "auth", "private_key",
    # the tenant's envelope key wrapped under the master key — cryptographic
    # secret material, must never ride a portable archive
    "wrapped_key",
    # derived, regenerated by the database on insert (migration 111) — dead
    # weight in an archive and unwritable on restore
    "search_text",
    # encrypted EIN blob — entities.py guarantees the raw EIN never leaves via
    # list/get (only ein_last4; reveal is a separate gated call), and this bulk
    # export must honor the same invariant
    "ein_enc",
}


def _select(conn, table: str):
    """(sql, cols) for a table's exportable columns, or (None, []) if the
    table is unreadable / fully excluded."""
    from psycopg import sql
    try:
        cols = [r["column_name"] for r in conn.execute(
            """SELECT column_name FROM information_schema.columns
               WHERE table_schema='public' AND table_name=%s
               ORDER BY ordinal_position""", (table,)).fetchall()]
    except Exception:                                     # noqa: BLE001
        return None, []
    keep = [c for c in cols if c not in _EXCLUDE_COLS]
    if not keep:
        return None, []
    return sql.SQL("SELECT {} FROM {}").format(
        sql.SQL(", ").join(sql.Identifier(c) for c in keep),
        sql.Identifier(table)), keep


def _dump_table(conn, table: str, fh) -> int:
    """Stream one table into `fh` as a JSON array. Returns the row count.

    Reading the whole table into a list, serialising that to one JSON
    string and writing it into an in-memory ZIP would hold three full copies
    of the largest table at once, on a small host; a large
    ledger is tens of thousands of rows, so an export would spike memory far
    past anything else the process does.

    Instead: a SERVER-SIDE cursor (named) so Postgres streams rather than
    shipping the whole result, and each row is serialised and written
    straight through. Peak memory is one row plus the zip's deflate window.
    """
    q, keep = _select(conn, table)
    fh.write("[\n")
    n = 0
    if q is not None:
        # named cursor => server-side; itersize bounds the client-side
        # prefetch. Must run inside a transaction to hold the portal open.
        with conn.transaction():
            with conn.cursor(name=f"exp_{table}") as cur:
                cur.itersize = 1000
                cur.execute(q)
                for r in cur:
                    row = {k: _json_safe(v) for k, v in zip(keep, r)} \
                        if not isinstance(r, dict) else \
                        {k: _json_safe(v) for k, v in r.items()}
                    # _EXCLUDE_COLS is a COLUMN filter and tenant_settings
                    # hides everything in one config JSONB — which carries
                    # smtp_password/plaid_secret/llm_api_key/mx_api_key
                    # ciphertext, cleartext provider identifiers and
                    # demo_login's plaintext password, none of which may ride
                    # an archive whose manifest says 'secrets are NEVER
                    # exported'. Same deep scrub the data-portability route
                    # applies.
                    if table == "tenant_settings" and row.get("config"):
                        from .sync.restore import scrub_config
                        cfg = row["config"]
                        if isinstance(cfg, str):
                            try:
                                cfg = json.loads(cfg)
                            except ValueError:
                                cfg = None
                        if isinstance(cfg, dict):
                            row["config"] = scrub_config(cfg)
                    if n:
                        fh.write(",\n")
                    fh.write(json.dumps(row, ensure_ascii=False))
                    n += 1
    fh.write("\n]\n")
    return n


def _json_safe(v):
    if isinstance(v, (dt.date, dt.datetime)):
        return v.isoformat()
    if isinstance(v, (bytes, memoryview)):
        return f"<{len(bytes(v))} bytes omitted>"
    try:
        json.dumps(v)
        return v
    except TypeError:
        return str(v)


def rls_tenant_tables(conn) -> list[str]:
    """The tables safe to bulk-export over the tenant RLS connection: a
    table having a tenant_id column is NOT enough — `users`, `invites`,
    and `api_tokens` carry tenant_id but have NO row-level security, so a
    plain SELECT over the app role would return EVERY tenant's rows (a
    cross-tenant PII breach). Export ONLY tables whose
    RLS is actually enabled (`pg_class.relrowsecurity`); any future no-RLS
    tenant_id table then can't silently rejoin the export. `users` is
    exported separately, correctly scoped, in the manifest.

    Catalog reads only, so any connection works (admin or tenant-scoped);
    the user-facing /export ZIP shares this discovery."""
    tid_tables = {r["table_name"] for r in conn.execute(
        """SELECT DISTINCT table_name FROM information_schema.columns
           WHERE table_schema='public' AND column_name='tenant_id'""").fetchall()}
    rls_tables = {r["relname"] for r in conn.execute(
        """SELECT c.relname FROM pg_class c
           JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname='public' AND c.relkind='r'
             AND c.relrowsecurity""").fetchall()}
    return sorted(tid_tables & rls_tables)


def control_tenant_tables(conn) -> list[str]:
    """The other half of the schema: tables carrying `tenant_id` with NO
    row-level security.

    `rls_tenant_tables` deliberately refuses these — an unscoped SELECT over
    the app role would return every tenant's rows — which also means neither
    export door can ever DISCOVER one. They have to be named by hand, and a
    hand-maintained list drifts: a table added after the tuple below was
    written is quietly missing from both doors, and nothing says so. A
    `recipient_invites` left out takes the addresses a household shares its
    financial mail with, and each one's consent stamp, out of a portability
    archive that claims to be complete.

    So the lists are not the record: this function is, and a guard test
    makes every table it returns a table some door has classified —
    exported, or excluded for a stated reason. A new control-plane table
    fails that test until somebody decides which."""
    tid_tables = {r["table_name"] for r in conn.execute(
        """SELECT DISTINCT table_name FROM information_schema.columns
           WHERE table_schema='public' AND column_name='tenant_id'""").fetchall()}
    rls_tables = {r["relname"] for r in conn.execute(
        """SELECT c.relname FROM pg_class c
           JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname='public' AND c.relkind='r'
             AND c.relrowsecurity""").fetchall()}
    return sorted(tid_tables - rls_tables)


# Control-plane tables the portable archive builds by hand, with their own
# SELECT and their own manifest key ("users", "mobile_devices"), so they are
# not in the generic loop below.
ARCHIVE_HAND_BUILT = frozenset({"users", "device_tokens"})

# …and the ones read generically by `_control_rows`, each landing in the
# manifest under its own name.
ARCHIVE_CONTROL_TABLES = ("invites", "api_tokens", "push_subscriptions",
                          "recipient_invites", "support_consents")

# Control-plane tables a portability archive deliberately leaves out. Each
# entry states WHY, because "it isn't in the list" is not a decision anyone
# can review later.
ARCHIVE_CONTROL_SKIP = {
    "sessions": "live login state — a token hash plus the IP and browser of "
                "an in-flight session. Credential material with a lifetime "
                "measured in days, not a record of the household.",
} | ext.gate.export_exclusions()

_CREDENTIAL_COL = ("token", "hash", "secret", "endpoint", "p256dh",
                   "auth", "password", "key")


def _control_rows(admin, table: str, tenant_id: str) -> list[dict]:
    """Metadata rows of one control-plane table for a tenant — columns
    chosen by name so a future credential column never rides out."""
    cols = [r["column_name"] for r in admin.execute(
        """SELECT column_name FROM information_schema.columns
            WHERE table_schema='public' AND table_name=%s
            ORDER BY ordinal_position""", (table,)).fetchall()
        if r["column_name"] not in _EXCLUDE_COLS
        and r["column_name"] != "tenant_id"
        and not any(w in r["column_name"] for w in _CREDENTIAL_COL)]
    if not cols:
        return []
    from psycopg import sql
    return admin.execute(
        sql.SQL("SELECT {} FROM {} WHERE tenant_id = %s").format(
            sql.SQL(", ").join(sql.Identifier(c) for c in cols),
            sql.Identifier(table)), (tenant_id,)).fetchall()


def build_archive(tenant_id: str, *, operator: str,
                  consented: bool, now: dt.datetime | None = None) -> bytes:
    """Return a ZIP (bytes) of the tenant's data as JSON. `operator` and
    `consented` are recorded in the manifest for provenance."""
    now = now or dt.datetime.now(dt.timezone.utc)
    admin = tenancy.admin_connect()
    try:
        tenant = admin.execute(
            "SELECT id, name, created_at, status FROM tenants WHERE id=%s",
            (tenant_id,)).fetchone()
        users = admin.execute(
            """SELECT id, email, role, created_at, verified_at
               FROM users WHERE tenant_id=%s ORDER BY created_at""",
            (tenant_id,)).fetchall()
        # Hand-included like `users`: device_tokens is a control-plane
        # table (tenant_id, no RLS), so the RLS-driven table discovery
        # below can never pick it up — yet a phone enrolled against the
        # tenant is personal data a portability request must cover.
        # Metadata only: device name, platform, lifecycle timestamps.
        # Never the token hash (a credential) nor the push token (a
        # platform routing identifier), same doctrine as password hashes.
        devices = admin.execute(
            """SELECT user_id, device_name, platform, created_at,
                      last_seen, expires_at, revoked_at
               FROM device_tokens WHERE tenant_id=%s
               ORDER BY created_at""", (tenant_id,)).fetchall()
        # the other control-plane tables that carry this tenant's personal
        # data with no RLS (so discovery cannot see them): who they
        # invited to the household, the script tokens they named, the
        # browsers they enrolled for push, the third parties they share
        # the daily mail with and what each one answered, and every grant
        # of support access they gave. Metadata only — every
        # credential-shaped column (token, hash, endpoint, keys) stays
        # behind. The membership of this set is guarded by a test — a
        # hand-maintained list is exactly the thing that drifts.
        control = {t: _control_rows(admin, t, tenant_id)
                   for t in ARCHIVE_CONTROL_TABLES}
        tables = rls_tenant_tables(admin)
    finally:
        admin.close()
    if tenant is None:
        raise ValueError("no such tenant")

    manifest = {
        "export_format": "oikonome-tenant-export/1",
        "generated_at": now.isoformat(),
        "generated_by_operator": operator,
        "tenant_consent_on_file": consented,
        "tenant": {"id": str(tenant["id"]), "name": tenant["name"],
                   "created_at": _json_safe(tenant["created_at"]),
                   "status": tenant["status"]},
        "users": [{k: _json_safe(v) for k, v in u.items()} for u in users],
        "mobile_devices": [{k: _json_safe(v) for k, v in d.items()}
                           for d in devices],
        **{t: [{k: _json_safe(v) for k, v in r.items()} for r in rows]
           for t, rows in control.items()},
        "tables": {},
        "notes": ["Secrets (tokens, TOTP seeds, password hashes) and file "
                  "blobs are excluded by design; blob rows carry metadata "
                  "only."],
    }

    buf = io.BytesIO()
    conn = tenancy.tenant_connect(tenant_id)
    try:
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
            for t in tables:
                # write THROUGH the zip member instead of building the whole
                # JSON string first — the deflater sees the rows
                # as they come off the cursor
                with z.open(f"data/{t}.json", "w") as raw:
                    fh = io.TextIOWrapper(raw, encoding="utf-8",
                                          write_through=True)
                    manifest["tables"][t] = _dump_table(conn, t, fh)
                    fh.flush()
                    fh.detach()
            z.writestr("manifest.json",
                       json.dumps(manifest, indent=1, ensure_ascii=False))
    finally:
        conn.close()
    return buf.getvalue()


# ---- consent (control-plane) ------------------------------------------------


def has_live_consent(admin, tenant_id: str,
                     now: dt.datetime | None = None) -> bool:
    now = now or dt.datetime.now(dt.timezone.utc)
    row = admin.execute(
        """SELECT 1 FROM support_consents
           WHERE tenant_id=%s AND revoked_at IS NULL AND expires_at > %s
           LIMIT 1""", (tenant_id, now)).fetchone()
    return row is not None


def consent_status(admin, tenant_id: str,
                   now: dt.datetime | None = None) -> dict | None:
    """The live grant's expiry + reason for the console, or None."""
    now = now or dt.datetime.now(dt.timezone.utc)
    row = admin.execute(
        """SELECT reason, expires_at, created_at FROM support_consents
           WHERE tenant_id=%s AND revoked_at IS NULL AND expires_at > %s
           ORDER BY expires_at DESC LIMIT 1""",
        (tenant_id, now)).fetchone()
    return dict(row) if row else None
