-- What a person changed a merchant's name to, and what it was before.
--
-- merchant_canonical holds ONE row per raw string, so writing a correction
-- overwrites whatever the automatic layers decided and the previous answer
-- is gone. That makes a user's own edit the least reversible thing in the
-- ledger, which is backwards: their edits are exactly the ones that should
-- be undoable, because they are the ones made from memory about a shop they
-- visited two years ago.
--
-- So every user-made naming change is recorded here first: the raw string,
-- what it displayed as before (NULL when nothing had mapped it), and what
-- it displays as now. Undo replays a row backwards. It also gives the
-- merchants screen its recent-changes list, and it is the only labelled
-- data about merchant identity this app will ever get — a correction is
-- ground truth in a way no heuristic is.
CREATE TABLE IF NOT EXISTS merchant_renames (
    tenant_id      UUID NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::uuid,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    raw_merchant   TEXT NOT NULL,
    from_canonical TEXT,
    to_canonical   TEXT NOT NULL,
    at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id)
);

CREATE INDEX IF NOT EXISTS merchant_renames_at
    ON merchant_renames (tenant_id, at DESC);

DO $$
BEGIN
    EXECUTE 'ALTER TABLE merchant_renames ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS tenant_isolation ON merchant_renames';
    EXECUTE
        'CREATE POLICY tenant_isolation ON merchant_renames '
        'USING (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid) '
        'WITH CHECK (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)';
END $$;

-- Restore replays the journal with its original ids, then setval()s the
-- identity sequence past them; setval requires UPDATE on the sequence,
-- which the blanket app-role grant (USAGE, SELECT) does not carry.
GRANT USAGE, SELECT, UPDATE ON SEQUENCE merchant_renames_id_seq
    TO oikonome_app;
