#!/usr/bin/env python3
"""Emit the version_history.tsv rows for gen-version-history.sh.

Three git invocations total, no per-commit shelling:
  1. `git grep -c '' <tag>` — the baseline line count of every tracked text
     file AT the tag, summed once.
  2. `git for-each-ref refs/tags` — the series anchors (see below).
  3. `git log --numstat` from the tag to HEAD — insertions/deletions per
     file per commit, applied as a running delta on top of the baseline.
     Binary files report "-" for both columns and are skipped (no line
     count to add).

Numbering follows `git describe` (the rule install.sh collapses a describe
with, scripts/version-stamp.sh): a version is `vA.B.N` where N counts
commits since that series' `vA.B.0` anchor tag. The history spans more than
one series, so the walk switches series the moment it reaches a commit that
carries a `vA.B.0` tag: that commit IS `vA.B.0`, the count restarts there,
and every earlier commit keeps the label it has always had. Versions
already shipped never get renumbered by a later series starting.

The line count is an approximation (a renamed-with-no-change file nets to
the same total either way, which is what we want; a file that's
binary-then-text across its history is the one edge case that under/over-
counts slightly) — good enough for an admin-console trend line, not an
accounting figure.
"""
from __future__ import annotations

import re
import subprocess
import sys

# A series anchor: the vA.B.0 tag every vA.B.N is counted from.
ANCHOR_RE = re.compile(r"^v(\d+)\.(\d+)\.0$")


def _run(args: list[str]) -> str:
    return subprocess.run(args, capture_output=True, text=True,
                          check=True).stdout


def baseline_loc(tag: str) -> int:
    out = _run(["git", "grep", "-c", "", tag])
    total = 0
    for line in out.splitlines():
        # "tag:path:count" — count is always the last field
        try:
            total += int(line.rsplit(":", 1)[1])
        except (IndexError, ValueError):
            continue
    return total


def series_anchors() -> dict[str, str]:
    """{commit sha: "vA.B"} for every series-anchor tag in the repo.

    An annotated tag's own object is not the commit, so both the object and
    its dereferenced target are mapped — whichever the log reports wins.
    """
    out = _run(["git", "for-each-ref", "--format=%(refname:strip=2)\t"
                "%(objectname)\t%(*objectname)", "refs/tags/v*"])
    anchors: dict[str, str] = {}
    for line in out.splitlines():
        name, obj, deref = (line.split("\t") + ["", ""])[:3]
        m = ANCHOR_RE.match(name)
        if not m:
            continue
        for sha in (obj, deref):
            if sha:
                anchors[sha] = f"v{m.group(1)}.{m.group(2)}"
    return anchors


def main() -> None:
    tag = sys.argv[1]
    series = tag.rsplit(".", 1)[0]          # "v0.1.0" → "v0.1"
    anchors = series_anchors()
    running = baseline_loc(tag)
    print("# version\tiso-date\tsha\tsubject\tloc")
    print("# generated by scripts/gen-version-history.sh — do not hand-edit")
    print("# N in vA.B.N = commits since that series' vA.B.0 tag (same rule "
          "as install.sh); loc = running lines-of-code total at that commit")

    log = _run(["git", "log", "--reverse", "--numstat",
               "--format=COMMIT\t%h\t%H\t%ad\t%s", "--date=short",
               f"{tag}..HEAD"])
    n = 0
    commit: list[str] | None = None

    def emit(c: list[str]) -> None:
        nonlocal n, series
        anchor = anchors.get(c[1])
        if anchor is not None and anchor != series:
            series, n = anchor, 0        # this commit IS the new vA.B.0
        else:
            n += 1
        print(f"{series}.{n}\t{c[2]}\t{c[0]}\t{c[3]}\t{running}")

    for line in log.splitlines():
        if line.startswith("COMMIT\t"):
            if commit is not None:
                emit(commit)
            _, short, full, date, subject = line.split("\t", 4)
            commit = [short, full, date, subject]
            continue
        if not line.strip() or commit is None:
            continue
        added, deleted, _path = line.split("\t", 2)
        if added == "-" or deleted == "-":
            continue                       # binary file — no line count
        running += int(added) - int(deleted)
    if commit is not None:
        emit(commit)


if __name__ == "__main__":
    main()
