"""Drift guard: every tenant-scoped (RLS + tenant_id) table must be a
CONSCIOUS decision for the user-facing /export + restore round trip — either
restored by sync.restore.restore_zip, or on an explicit skip-list
(operational, derived, or secret data that must not travel). A whole domain's
tables can otherwise fall silently through the gap; this test fails the
moment a new RLS table is added and not classified, forcing the choice."""
import unittest

from oikonome.db import tenancy

from .util import _ensure_db

# Tables sync/restore.py round-trips (product→product export/restore).
RESTORED = {
    "items", "accounts", "transactions", "bills", "manual_categories",
    "reimbursements", "reimburse_flags", "business_flags", "liabilities",
    "holdings", "crypto_holdings", "networth_recorded", "networth_snapshot",
    "income_annual", "income_documents", "merchant_canonical", "merchants",
    "merchant_renames", "merchant_categories", "amazon_orders", "amazon_matches",
    "amazon_summaries", "costco_receipts", "costco_matches",
    # the merge offers AND the decisions on them: a rejected pair is only
    # kept apart by its (deterministic) proposal row, so dropping the table
    # re-offers every pair the household already turned down
    "merchant_merge_proposals",
    "tenant_settings", "business_entity",
    "entity_membership", "equity_movement", "business_txn_class",
    "compliance_obligation", "mileage_log", "vendor_1099", "transaction_notes",
    "budget_snapshots",
    # the shadow set: without it a round trip un-shadows every duplicate
    # source of the same real account and the money aggregates double-count
    "account_links",
}

# Intentionally NOT round-tripped, with the reason. If you add a table here,
# say why it doesn't belong in a user's data export/restore.
SKIP = {
    "bill_proposals": "regenerated by nightly detection",
    "alerts_log": "log, regenerated",
    "import_batches": "import history/scratch",
    "import_staging": "import scratch",
    "job_progress": "job bookkeeping",
    "job_runs": "job bookkeeping / heartbeats",
    "feedback_reports": "operational ring buffer (off on hosted)",
    "sync_log": "sync history",
    "account_adoptions": "reconnect bookkeeping — instance-local, and exporting it\n                          would tell a fresh instance to drop a backfill it does not have",
    "script_heartbeats": "collector heartbeats",
    "tenant_keys": "envelope key — SECRET, must never export",
    "receipts": "receipt images — bytes excluded from export by design",
    "receipt_items": "receipt line items tied to excluded images",
    "categorizer_model": "learned overlay — derived cache, retrained "
                         "nightly from merchant_categories (round-tripped)",
}


class TenantTableCoverageTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        _ensure_db()

    def test_every_rls_tenant_table_is_classified(self):
        admin = tenancy.admin_connect()
        try:
            rows = admin.execute(
                """SELECT t.table_name FROM information_schema.tables t
                   JOIN information_schema.columns col
                     ON col.table_name = t.table_name
                        AND col.column_name = 'tenant_id'
                   JOIN pg_class pc ON pc.relname = t.table_name
                   WHERE t.table_schema = 'public' AND pc.relrowsecurity""",
                ).fetchall()
        finally:
            admin.close()
        live = {r["table_name"] for r in rows}
        classified = RESTORED | set(SKIP)
        unclassified = live - classified
        self.assertEqual(
            unclassified, set(),
            f"New RLS+tenant_id table(s) {sorted(unclassified)} are neither "
            f"restored by sync/restore.py nor on the SKIP list. Decide: does a "
            f"user's data export/restore need this table? Add it to restore.py "
            f"+ RESTORED, or to SKIP with a reason.")
        # and don't let the lists rot with names that no longer exist
        stale = classified - live
        self.assertEqual(stale, set(),
                         f"classified tables no longer in the schema: {sorted(stale)}")

    def test_export_discovery_sees_new_rls_tables_and_never_no_rls_ones(self):
        """rls_tenant_tables is the membership source for BOTH exports
        (the portable archive and the user /export ZIP). Two invariants: a
        freshly added RLS+tenant_id table is picked up with no list to
        edit, and a tenant_id table WITHOUT row-level security (users,
        invites, api_tokens — a plain SELECT there is every tenant's
        rows) can never appear."""
        from oikonome.tenant_export import rls_tenant_tables

        class _Rollback(Exception):
            pass

        admin = tenancy.admin_connect()
        try:
            try:
                with admin.transaction():
                    admin.execute(
                        "CREATE TABLE _cov_probe (tenant_id uuid, v text)")
                    admin.execute("ALTER TABLE _cov_probe "
                                  "ENABLE ROW LEVEL SECURITY")
                    tabs = set(rls_tenant_tables(admin))
                    self.assertIn("_cov_probe", tabs)
                    for no_rls in ("users", "invites", "api_tokens"):
                        self.assertNotIn(no_rls, tabs)
                    # never committed — the schema stays untouched
                    raise _Rollback
            except _Rollback:
                pass
        finally:
            admin.close()


if __name__ == "__main__":
    unittest.main()
