"""The installable-web-app manifest and its icons.

A manifest that names an icon which is not on disk fails silently: the
browser just falls back (on iOS, to a screenshot of the page), and nothing
logs, 404s in a way anyone notices, or breaks a page. So the wiring is
pinned here rather than trusted.

Icons are generated by ``scripts/gen-app-icons.py`` from the SVG masters;
that script's ``--check`` mode verifies the pixels still match the SVG, but
it needs cairosvg, which the test venv does not carry. These tests need
nothing but the files.
"""

import json
import pathlib
import re
import struct
import unittest

WEBAPP = pathlib.Path(__file__).resolve().parents[2] / "webapp"
PUBLIC = WEBAPP / "public"
MANIFEST = PUBLIC / "manifest.webmanifest"


def _png_size(path: pathlib.Path) -> tuple[int, int]:
    """(width, height) straight out of the IHDR chunk — no PIL needed."""
    raw = path.read_bytes()
    if raw[:8] != b"\x89PNG\r\n\x1a\n":
        raise AssertionError(f"{path.name} is not a PNG")
    return struct.unpack(">II", raw[16:24])


def _served_path(src: str) -> pathlib.Path:
    """Manifest srcs are absolute URLs under /app/, which is this dir."""
    assert src.startswith("/app/"), src
    return PUBLIC / src[len("/app/"):]


class ManifestIcons(unittest.TestCase):
    def setUp(self):
        self.manifest = json.loads(MANIFEST.read_text())

    def test_every_icon_exists(self):
        icons = self.manifest["icons"]
        self.assertTrue(icons)
        for icon in icons:
            p = _served_path(icon["src"])
            self.assertTrue(p.is_file(), f"{icon['src']} is in the manifest "
                                         f"but not on disk")

    def test_png_icons_are_the_size_they_claim(self):
        for icon in self.manifest["icons"]:
            if icon["type"] != "image/png":
                continue
            w, h = _png_size(_served_path(icon["src"]))
            self.assertEqual(f"{w}x{h}", icon["sizes"],
                             f"{icon['src']} is {w}x{h}")

    def test_a_maskable_icon_is_offered(self):
        """Without one, Android masks the rounded-corner 'any' icon and the
        transparent corners show inside its own shape."""
        purposes = {i.get("purpose") for i in self.manifest["icons"]}
        self.assertIn("maskable", purposes)

    def test_apple_touch_icon_is_declared_and_present(self):
        """iOS reads no manifest icons at all and ignores SVG, so this link
        is the only thing standing between a home-screen install and a
        screenshot of the page."""
        html = (WEBAPP / "index.html").read_text()
        m = re.search(r'rel="apple-touch-icon"[^>]*href="([^"]+)"', html)
        self.assertIsNotNone(m, "index.html declares no apple-touch-icon")
        p = _served_path(m.group(1))
        self.assertTrue(p.is_file(), f"{m.group(1)} is missing")
        # Apple wants a square, opaque icon; 180 is the current home-screen
        # size and downscales cleanly to the older ones.
        self.assertEqual(_png_size(p), (180, 180))

    def test_standalone_launch_is_declared_for_both_platforms(self):
        html = (WEBAPP / "index.html").read_text()
        self.assertEqual(self.manifest["display"], "standalone")
        # the standard name and the one iOS actually honours
        self.assertIn('name="mobile-web-app-capable"', html)
        self.assertIn('name="apple-mobile-web-app-capable"', html)


if __name__ == "__main__":
    unittest.main()
